---
- name: "Install Node.js 13"
  become: true
  shell: |
    # Install Node.js LTS version as our base Node.js version
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -
    sudo apt install -y nodejs
    # Use n version manager to use Node.js v13.8.0
    sudo npm install --global n
    sudo n 13.8.0
- name: "Install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes


# ---
# - name: "Add Node.js from Nodesource"
#   become: true
#   shell: |
#     curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

# - name: "install dependencies."
#   become: true
#   apt:
#     name: ["nodejs", "npm"]
#     state: latest
#     update_cache: yes

# - name: "install PM2 Globally"
#   become: true
#   npm:
#     name: pm2
#     global: yes
    