---
- name: "Add Node.js from Nodesource"
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "install dependencies."
  become: true
  apt:
    name: ["nodejs", "npm"]
    state: latest
    update_cache: yes

- name: "install PM2 Globally"
  become: true
  npm:
    name: pm2
    global: yes
    